package com.teragrep.aer_02;

import org.junit.Test;
import org.junit.jupiter.api.Disabled;

/**
 * Unit test for Function class.
 */
public class SyslogBridgeTest {
    /**
     * Unit test for hello method.
     */
    @Disabled(value = "generated by archetype, implement SyslogBridge tests")
    @Test
    public void testHello() throws Exception {
       // final Function function = new Function();

       // final String ret = function.hello("function", null);

       // assertEquals("Hello, function!", ret);
    }
}
